[package]
name = "Password-Program"
version = "0.1.0"
edition = "2021"
authors = ["Alec <apb718@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"